//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IA_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Request
    {
        public int request_id { get; set; }
        public Nullable<int> id_professor { get; set; }
        public Nullable<int> id_TeamLeader { get; set; }
        public string status { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual TeamLeader TeamLeader { get; set; }
    }
}
